# Generated by Django 4.1 on 2022-09-04 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tareasTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombreTarea', models.CharField(max_length=100, verbose_name='nombreTarea')),
                ('fechaIncio', models.DateField(auto_now=True, verbose_name='fechaIncio')),
                ('plazoParaTerminar', models.DateField(verbose_name='plazoParaTerminar')),
            ],
        ),
    ]
