# Generated by Django 4.1 on 2022-09-04 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareastable',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
