# Generated by Django 4.1 on 2022-09-04 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolistApp', '0002_alter_tareastable_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tareastable',
            name='nombreTarea',
            field=models.CharField(max_length=100, verbose_name='Nombre de la Tarea'),
        ),
        migrations.AlterField(
            model_name='tareastable',
            name='plazoParaTerminar',
            field=models.DateField(verbose_name='Plazo Para terminar'),
        ),
    ]
